DEBUG = True
BCRYPT_LEVEL = 12
MAIL_FROM = "someone@somewhere.com"

RECAPTCHA_PUBLIC_KEY = "6LcIFAITAAAAAEQZFaKrW3DoDVyeux4iSk9yJItk"
RECAPTCHA_PRIVATE_KEY = "6LcIFAITAAAAAIQwieMGyB5dGCbOmwgoIufLzsVH"

MONGODB_SETTINGS = {'DB' : 'ctfdb'}
SECRET_KEY = 'Oooooh!S3cr3T!!!!'

